# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Matt J Owen
description:      'A mathematical biologist, specialising in computational tools and machine learning for cardiovascular sciences'
url:              https://mjowen.github.io/
baseurl:          /

author:
  name:           'Matt J Owen'
  url:            https://twitter.com/MattJOwen_

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mjowen
